TestCase#3
speee/testeee pull request #4
Opened 2019-09-25 08:17 UTC by teppei-komata

Test Caseクラスを作成しました。
遅くなりましてすいません、、
よろしくお願いします。

2019-09-30 00:19 UTC, kou requested changes
遅いとか早いとかはないので大丈夫です！

2019-09-30 00:19 UTC, kou commented on testeee.rb
> +  success.test # -> "OK"
#3 にあるように`success.run`でテストを実行するようにしてみてください！

2019-09-30 00:20 UTC, kou commented
追加の変更はこのbranchにpushすれば大丈夫です！

2019-10-04 02:24 UTC, teppei-komata commented
methodにaliasをつけてrunで実行するようにしました。

2019-10-04 02:29 UTC, kou commented
`run`は`TestCase`を使うユーザー側ではなく、`TestCase`が提供してください！
（テスティングフレームワークの一部として実装してください！）

2019-10-04 11:09 UTC, teppei-komata commented
理解が足らずすいません。
evalメソッドを使ってTestCaseに実装しました。

2019-10-07 00:29 UTC, kou commented
いい感じに難しく考えすぎましたね！

↓で十分じゃないですか！？

```ruby
  def run
    test
  end
```

2019-10-07 02:15 UTC, teppei-komata commented
なるほど！確かに難しく考えすぎてました。
eval削除しました。

2019-10-07 03:31 UTC, kou approved these changes
さすがです！

2019-10-07 03:31 UTC, merged